name: build artifact
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build Assets
        run: npm run build:manual
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Test Download
        run: ls -R
